# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2b2d0e6a5f8835a29481bc139ed2572674bbcb35139d7a46d6e9343741fbbb2b386838df58dd0d46d4e173569ecb4bb83ff65bc72b3df839c40256f07022ce3

test:
  secret_key_base: 21ab5fd43f8159a3c02e868620a980f9a45b27debd5b64d35a72461b140aa564d4f73cfbf7c1e43826fd0abf8626304d4dce27b330d55700debe538871cdc1ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
